# etcd certificate generation
---

- set_fact:
    basedir: /etc/etcd
  when: not local

- set_fact:
    basedir: "."
  when: local


- name: install cfssl
  get_url:
    url: "{{item.url}}"
    dest: "{{item.dest}}"
    mode: 755
  with_items:
    - url: https://pkg.cfssl.org/R1.2/cfssl_linux-amd64
      dest: /tmp/cfssl

    - url: https://pkg.cfssl.org/R1.2/cfssljson_linux-amd64
      dest: /tmp/cfssljson

- name: ensure etcd config directory exists
  file:
    path: /etc/etcd
    state: directory
  when: not local

- name: generate ca config
  template:
    src: ca-config.json.j2
    dest: "{{basedir}}/ca-config.json"

- name: generate ca csr
  template:
    src: ca-csr.json.j2
    dest: "{{basedir}}/ca-csr.json"

- name: generate db config
  template:
    src: db-config.json.j2
    dest: "{{basedir}}/db-config.json"

- name: generate db csr
  template:
    src: db-csr.json.j2
    dest: "{{basedir}}/db-csr.json"

- name: generate ca certs
  shell: > 
    /tmp/cfssl gencert -initca ca-csr.json | 
    /tmp/cfssljson -bare ca
  args:
    chdir: "{{basedir}}"

- name: generate db certs
  shell: >
    /tmp/cfssl gencert
    -ca=ca.pem
    -ca-key=ca-key.pem
    -config=db-config.json
    -hostname={{ auth_hosts | join(',') }}
    -profile={{db.profile}}
    db-csr.json | /tmp/cfssljson -bare db
  args:
    chdir: "{{basedir}}"
    
