# etcd setup
---

- name: create etcd configuration dirs
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /etc/etcd
    - /var/lib/etcd

- include_tasks: fetch.yml

- name: copy certs
  copy:
    src: "{{item.src}}"
    dest: "{{item.dest}}"
  with_items:
    - src: "{{ca_pem}}"
      dest: /etc/etcd/ca.pem

    - src: "{{db_pem}}"
      dest: /etc/etcd/db.pem

    - src: "{{db_key}}"
      dest: /etc/etcd/db-key.pem
  when: not keygen

- name: add etcd service file
  template:
    src: etcd.service.j2
    dest: /etc/systemd/system/etcd.service

- name: enable etcd
  systemd:
    name: etcd
    enabled: yes
    daemon_reload: yes

- name: start etcd
  systemd:
    name: etcd
    state: restarted
