# etcd setup
---

# because it takes 1-2 tries to get the correct dns response from the correct dns entity
- name: docker pull etcd image
  command: docker pull bitnami/etcd:{{ version }}
  retries: 6
  delay: 5
  register: result
  until: result.rc == 0

# TODO: permissions for container, run as different user
- name: ensure etcd config dir does not exist
  file:
    path: /etc/etcd
    state: absent
  when: not keygen

- name: create etcd config directory
  file:
    path: /etc/etcd
    state: directory
    mode: '0777'
  when: not keygen

- name: copy certs
  copy:
    src: "{{item.src}}"
    dest: "{{item.dest}}"
    mode: '0755'
  with_items:
    - src: "{{ca_pem}}"
      dest: /etc/etcd/ca.pem

    - src: "{{db_pem}}"
      dest: /etc/etcd/db.pem

    - src: "{{db_key}}"
      dest: /etc/etcd/db-key.pem
  when: not keygen

- name: set cert permissions
  file:
    path: "{{item}}"
    mode: '0755'
  with_items:
    - /etc/etcd/ca.pem
    - /etc/etcd/db.pem
    - /etc/etcd/db-key.pem
  when: keygen
