# etcd setup
---

- name: add mergetb {{release}} repo
  shell: curl https://pkg.mergetb.net/addrepo | RELEASE={{release}} bash - 
  args:
    creates: /etc/apt/sources.list.d/mergetb-{{release}}.list

- name: install etcd
  apt:
    name: etcd
    update_cache: yes

- name: ensure etcd config dir
  file:
    path: /etc/etcd
    state: directory
    owner: etcd
    group: etcd

- name: copy certs
  copy:
    src: "{{item.src}}"
    dest: "{{item.dest}}"
  with_items:
    - src: "{{ca_pem}}"
      dest: /etc/etcd/ca.pem

    - src: "{{db_pem}}"
      dest: /etc/etcd/db.pem

    - src: "{{db_key}}"
      dest: /etc/etcd/db-key.pem
  when: not keygen and not encrypted

- name: disable default etcd instance
  systemd:
    name: etcd
    enabled: no
    state: stopped
