# etcd setup
---

- name: docker pull etcd image
  command: docker pull bitnami/etcd:{{ version }}

# TODO: permissions for container, run as different user
- name: ensure etcd config dir does not exist
  file:
    path: /etc/etcd
    state: absent

- name: create etcd config directory
  file:
    path: /etc/etcd
    state: directory
    mode: '0777'

- name: copy certs
  copy:
    src: "{{item.src}}"
    dest: "{{item.dest}}"
    mode: '0755'
  with_items:
    - src: "{{ca_pem}}"
      dest: /etc/etcd/ca.pem

    - src: "{{db_pem}}"
      dest: /etc/etcd/db.pem

    - src: "{{db_key}}"
      dest: /etc/etcd/db-key.pem
  when: not keygen
