---

- name: generate etcd cluster keys
  include_tasks: gencerts.yml
  when: keygen

- name: install docker
  include_tasks: prereqs.yml
  when: proxy or server

- name: install etcd server
  include_tasks: server.yml
  when: server

- name: install etcd proxy
  include_tasks: proxy.yml
  when: proxy
