---

- name: ensure etcd is setup
  include_tasks: install.yml

- name: add etcd server service
  template:
    src: etcd.service
    dest: /etc/systemd/system/etcd-server.service

- name: enable and run etcd-server service
  systemd:
    name: "{{ server_name }}"
    enabled: yes
    state: restarted
    daemon_reload: yes
